##################################################
## class Les
##################################################
setClass("Les",
  representation(pos="integer",
                 chr="factor",
                 lambda="numeric",
                 se="numeric",
                 nProbes="integer",
                 pval="numeric",
                 win="integer",
                 weighting="function",
                 grenander="logical",
                 ci="data.frame",
                 nBoot="integer",
                 conf="numeric",
                 subset="integer",
                 theta="numeric",
                 nSigProbes="numeric",
                 regions="data.frame",
                 limit="numeric",
                 nChr="integer",
                 minLength="integer",
                 maxGap="numeric",
                 minProbes="integer",
                 method="character")
)
